# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jk-klUeIPulOjpU2F3GztjPokbICMvcl
"""

import pandas as pd

my_path="/content/sample_data/Customer_Category_Matrix.csv"
ccm = pd.read_csv(my_path,sep=";")
ccm.head()

my_path2="/content/sample_data/Customer_Features.csv"
cf=pd.read_csv(my_path2,sep=";")
cf.head()

my_path3="/content/sample_data/Product_Features.csv"
pf=pd.read_csv(my_path3,sep=";")
pf.head()

my_path4="/content/sample_data/StockCode_Detail_Raw.csv"
sd=pd.read_csv(my_path4,sep=";")
sd.head()

"""
Hybrid Recommendation System — adapted to the actual project dataset
----------------------------------------------------------------------
Data available:
  - Customer_Features.csv        : 1 row per customer, incl. PreferredProduct
  - Customer_Category_Matrix.csv : 1 row per customer, category spend/qty/share
  - Product_Features.csv         : 1 row per product (11 products)
  - StockCode_Detail_Raw.csv     : 1 row per SKU (1,000 SKUs, 11 descriptions)

There is NO transaction-level (customer x product) interaction log, so classic
item-based collaborative filtering (SVD over a ratings matrix) cannot be used.

Instead:
  - Collaborative side: USER-BASED CF. Each customer is represented by a
    numeric profile (category shares + spending behaviour). We find each
    customer's nearest-neighbour customers and let those neighbours "vote"
    on a product via their PreferredProduct field.
  - Content-based side: each product is scored using its own attributes
    (popularity, revenue, return rate) from Product_Features.
  - Hybrid: blend the neighbour-vote score with the content-based score,
    then pick the single best-performing StockCode (SKU) for the winner.

Requires: pandas, scikit-learn
Install with: pip install pandas scikit-learn --break-system-packages
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import NearestNeighbors

# ---------------------------------------------------------
# 1. Load and merge customer-level data
# ---------------------------------------------------------



# CF already has CategoryShare_* columns, so only bring the extra
# spend/qty columns in from CCM to avoid duplicate columns.
ccm_extra = ccm.drop(columns=[c for c in ccm.columns if c.startswith("CategoryShare_")])
customers = cf.merge(ccm_extra, on="CustomerID", how="left")

# ---------------------------------------------------------
# 2. Build a numeric customer profile for similarity search
# ---------------------------------------------------------

profile_cols = [
    "CategoryShare_Accessories", "CategoryShare_Apparel", "CategoryShare_Electronics",
    "CategoryShare_Furniture", "CategoryShare_Stationery",
    "PurchaseFrequency", "TotalSpending", "AverageOrderValue", "ReturnRate",
]

profile_matrix = customers[profile_cols].fillna(0)
scaler = MinMaxScaler()
profile_scaled = scaler.fit_transform(profile_matrix)

# ---------------------------------------------------------
# 3. Fit nearest-neighbour model (user-based collaborative filtering)
# ---------------------------------------------------------

K = 25  # number of similar customers to consider
knn = NearestNeighbors(n_neighbors=K + 1, metric="cosine")  # +1 to include self, dropped later
knn.fit(profile_scaled)


def neighbour_vote_scores(customer_id: int) -> pd.Series:
    """
    Find K customers most similar to `customer_id` and return a score per
    product based on how many of those neighbours prefer it (closer
    neighbours count more).
    """
    idx = customers.index[customers["CustomerID"] == customer_id][0]
    distances, indices = knn.kneighbors([profile_scaled[idx]])

    distances, indices = distances[0][1:], indices[0][1:]  # drop self (distance 0)
    similarity = 1 - distances  # cosine distance -> similarity

    neighbours = customers.iloc[indices].copy()
    neighbours["similarity"] = similarity

    votes = neighbours.groupby("PreferredProduct")["similarity"].sum()
    return votes / votes.sum() if votes.sum() > 0 else votes


# ---------------------------------------------------------
# 4. Content-based product scoring
# ---------------------------------------------------------



# Higher popularity + revenue is good; higher return rate is bad.
pf_scaled = pf.copy()
mm = MinMaxScaler()
pf_scaled[["PopRankScore", "RevenueScore"]] = mm.fit_transform(
    pf[["PopularityRank", "TotalRevenue"]]
)
pf_scaled["PopRankScore"] = 1 - pf_scaled["PopRankScore"]  # rank 1 = best, so invert
pf_scaled["ReturnPenalty"] = mm.fit_transform(pf[["ReturnRate"]])

pf_scaled["content_score"] = (
    0.5 * pf_scaled["PopRankScore"]
    + 0.4 * pf_scaled["RevenueScore"]
    - 0.1 * pf_scaled["ReturnPenalty"]
)
content_scores = pf_scaled.set_index("Description")["content_score"]


def best_stockcode_for(product_description: str) -> str:
    """Pick the single best-selling SKU for a given product description."""
    rows = sd[sd["Description"] == product_description]
    return rows.sort_values("TotalRevenue", ascending=False).iloc[0]["StockCode"]


# ---------------------------------------------------------
# 5. Hybrid blend
# ---------------------------------------------------------

CF_WEIGHT = 0.7  # trust neighbour voting more than raw product popularity


def hybrid_recommend(customer_id: int, top_n: int = 3):
    cf_scores = neighbour_vote_scores(customer_id)

    all_products = content_scores.index
    combined = pd.Series(0.0, index=all_products)
    for product in all_products:
        cf_part = cf_scores.get(product, 0.0)
        content_part = content_scores.get(product, 0.0)
        combined[product] = CF_WEIGHT * cf_part + (1 - CF_WEIGHT) * content_part

    top = combined.sort_values(ascending=False).head(top_n)

    results = []
    for product, score in top.items():
        sku = best_stockcode_for(product)
        results.append((product, sku, round(score, 4)))
    return results


if __name__ == "__main__":
    sample_customer = customers["CustomerID"].iloc[0]
    print(f"Hybrid recommendations for customer {sample_customer}:")
    for product, sku, score in hybrid_recommend(sample_customer):
        print(f"  {product} (best SKU: {sku}) -> score {score}")

"""
Evaluation script for the Hybrid Recommendation System
--------------------------------------------------------
Paste/import this AFTER your existing hybrid_recommendation.py code, since it
reuses: customers, cf, ccm, pf, sd, profile_cols, content_scores,
best_stockcode_for(), CF_WEIGHT, and hybrid_recommend().

WHY THIS APPROACH:
Your dataset has no per-transaction (customer x product) interaction log and
no explicit 1-5 star ratings, so you cannot compute "predicted rating vs
actual rating" MSE the classical way. Instead we treat each customer's
PreferredProduct as the single "ground truth" relevant item and evaluate
with LEAVE-ONE-OUT:

  1. For each customer, temporarily hide their real PreferredProduct.
  2. Rebuild neighbour voting using only the OTHER customers (so the model
     can't just "cheat" by reading the customer's own label back).
  3. Ask the hybrid model for its top-N product recommendations.
  4. Check whether the hidden true product appears in that top-N list.

From those hits/misses across all customers we get real Precision@N,
Recall@N and F1@N. For MSE, we score every (customer, product) pair as
relevant (1) if it's that customer's true PreferredProduct, else not
relevant (0), and compare that to the model's own combined_score
(min-max scaled to [0,1]) for that product. This is a proxy for how well
your scoring function separates "correct" products from the rest -- state
this assumption explicitly in your report, since it is not a true
rating-prediction MSE.

Requires: pandas, numpy, scikit-learn
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import mean_squared_error

TOP_N = 3  # how many recommendations count as a "hit" -- match what you report elsewhere


# ---------------------------------------------------------
# 1. Leave-one-out scorer: recommend for a customer WITHOUT
#    letting their own PreferredProduct influence the vote
# ---------------------------------------------------------

def hybrid_recommend_loo(customer_id, top_n=TOP_N):
    """
    Same logic as hybrid_recommend(), but excludes the target customer
    from the neighbour pool entirely (stronger than just excluding
    distance-0 self-matches -- this prevents leakage of their own label
    via any near-duplicate profile too).
    """
    idx = customers.index[customers["CustomerID"] == customer_id][0]

    mask = customers.index != idx
    pool = customers[mask].reset_index(drop=True)
    pool_scaled = profile_scaled[mask.to_numpy() if hasattr(mask, "to_numpy") else mask]

    k = min(25, len(pool) - 1)
    knn_loo = NearestNeighbors(n_neighbors=k, metric="cosine")
    knn_loo.fit(pool_scaled)

    distances, indices = knn_loo.kneighbors([profile_scaled[idx]])
    distances, indices = distances[0], indices[0]
    similarity = 1 - distances

    neighbours = pool.iloc[indices].copy()
    neighbours["similarity"] = similarity

    votes = neighbours.groupby("PreferredProduct")["similarity"].sum()
    cf_scores = votes / votes.sum() if votes.sum() > 0 else votes

    all_products = content_scores.index
    combined = pd.Series(0.0, index=all_products)
    for product in all_products:
        cf_part = cf_scores.get(product, 0.0)
        content_part = content_scores.get(product, 0.0)
        combined[product] = CF_WEIGHT * cf_part + (1 - CF_WEIGHT) * content_part

    return combined.sort_values(ascending=False)


# ---------------------------------------------------------
# 2. Run leave-one-out over every customer, collect hits
#    and per-pair scores for the metrics below
# ---------------------------------------------------------

def run_evaluation(top_n=TOP_N):
    y_true_all, y_score_all = [], []  # for MSE, flattened over every (customer, product) pair
    tp = fp = fn = 0

    for customer_id in customers["CustomerID"]:
        true_product = customers.loc[
            customers["CustomerID"] == customer_id, "PreferredProduct"
        ].iloc[0]

        combined = hybrid_recommend_loo(customer_id, top_n=top_n)
        top_products = set(combined.head(top_n).index)

        hit = true_product in top_products
        if hit:
            tp += 1
        else:
            fn += 1          # the true product was relevant but not recommended
        fp += len(top_products) - (1 if hit else 0)  # recommended-but-not-true items

        # --- pair-level data for MSE ---
        scaled = MinMaxScaler().fit_transform(combined.values.reshape(-1, 1)).flatten()
        scaled_scores = pd.Series(scaled, index=combined.index)
        for product in content_scores.index:
            y_true_all.append(1 if product == true_product else 0)
            y_score_all.append(scaled_scores.get(product, 0.0))

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    mse = mean_squared_error(y_true_all, y_score_all)

    return {
        "top_n": top_n,
        "n_customers": len(customers),
        "hits": tp,
        "precision@n": round(precision, 4),
        "recall@n": round(recall, 4),
        "f1@n": round(f1, 4),
        "mse": round(mse, 6),
    }


if __name__ == "__main__":
    results_by_weight = []

    for w in [0.0, 0.3, 0.5, 0.7, 1.0]:
        CF_WEIGHT = w
        result = run_evaluation(top_n=3)
        result["cf_weight"] = w
        results_by_weight.append(result)
        print(w, result)

    comparison_df = pd.DataFrame(results_by_weight)
    print(comparison_df[["cf_weight", "precision@n", "recall@n", "f1@n", "mse"]])

